### ISSUE TITLE
No check for invalid product id

### ISSUE THREAD

**Issue by Msait** [RobbyWD/ireland#3]
When type http://localhost:8080/web/products/-1 there is product = null
and as a result  on the view empty fields
![Uploading Screen Shot 2015-09-13 at 18.33.00.png…](issue)

PS: same issue with category

**Comment by RobbyWD** [comment]
I guess its cause nothing in the DB at this point:) Will check that out, thanks ;)

**Comment by RobbyWD** [comment]
Resolved.
