### ISSUE TITLE
styles does not loading

### ISSUE THREAD

**Issue by Msait** [RobbyWD/ireland#4]
maybe 

``` java
${pageContext.request.contextPath}/resources/css/shift.css
```

will help?

PS: same issue with category

**Comment by RobbyWD** [comment]
Thanks, told you bout that issue like ages ago, will give a try to your advice ;)

**Comment by Msait** [comment]
on management same story :+1:

**Comment by RobbyWD** [comment]
and the same with users, lad. I hope the method you've offered will fix that.

**Comment by RobbyWD** [comment]
Works as intended :)
